import turtle
turtle.color('red')
turtle.pendown()
turtle.forward(150)
turtle.right(144)
turtle.color('orange')
turtle.forward(150)
turtle.right(144)
turtle.color('green')
turtle.forward(150)
turtle.right(144)
turtle.color('blue')
turtle.forward(150)
turtle.right(144)
turtle.color('purple')
turtle.forward(150)
turtle.right(144)
